blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Suyajnaa/RegMap-AI-Offline-Compliance-Intelligence-Platform-forRegulatedBanking/discussions
    about: Please ask and answer questions here.
